
services:
  postgres:
    image: postgres:16-alpine
    container_name: book-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ${DB_DATA}:/var/lib/postgresql/data
    networks:
      - book-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: book-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
    depends_on:
      - postgres
    networks:
      - book-network
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
#      - /app/dist

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: book-frontend
    environment:
      VITE_API_URL: ${VITE_API_URL}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
    ports:
      - "5173:5173"  # Frontend op poort 5174
    depends_on:
      - backend
    networks:
      - book-network
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist

networks:
  book-network:
    driver: bridge

volumes:
  postgres_data:
